- src/plugins/repeater/model.py
> fix.修复主动发言的时候可能说出被ban的消息的bug

- src/plugins/roulette/__init__.py
- src/plugins/roulette/pseudorandom.py
1. Added pseudorandom for roulette **per group**. The probability of the `rand` will be decreased a little bit when it is chosen, and the probabilities of other numbers will increase.
2. Added pseudorandom for missing probability **per group**. The probability will increase a bit if the previous shot did not miss, and will reset when it missed.
> [Feature] Pseudorandom

- DeploymentTutorial.md
> 删除部署教程中过时的内容

- src/plugins/repeater/model.py
> fix: 加入定长队列，避免主动发言内容重复

- docs/AIDeployment.md
- src/plugins/chat/__init__.py
- src/plugins/chat/answer.py
- src/plugins/chat/requirements.txt
- src/plugins/greeting/wiki.py
- src/plugins/sing/__init__.py
- src/plugins/sing/requirements.txt
- src/plugins/sing/separater.py
- src/plugins/sing/svc_inference.py
> feat: ChatRWKV

- src/plugins/repeater/__init__.py
假 at 即为 `@群名片/昵称`，是纯文本的
我个人感觉真 at 还挺好玩的，所以这个 feature 我不会合，有需要的朋友可以自己合进去使用~
> feat.替换真at为假at（纯文本）

- .gitmodules
- .vscode/launch.json
- resource/sing/models/path_structure.txt
- src/plugins/sing/__init__.py
- src/plugins/sing/requirements.txt
- src/plugins/sing/separater.py
- src/plugins/sing/svc_inference.py
别忘了更新子模块哦（
```bash
git submodule update --init --recursive
```
另外由于默认切片长度变了，建议把之前缓存的音频全删了
> feat: support so-vits-svc 4.0 branch

- .github/workflows/build.yml
- Dockerfile
- docker-compose.yml
文档暂时懒得写，`docker-comopose up -d` 即可一键部署牛牛
> 支持GitHub Actions自动构建与docker一键部署

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Dockerfile
- docker-compose.yml
- docs/Deployment.md
> 添加 Docker 部署文档，修复构建bug

- src/plugins/sing/__init__.py
> feat: 自动清理 sing 插件的缓存

- src/plugins/block/__init__.py
> 重构: 抛弃 global 变量避免不可预知错误

- .env
- .github/workflows/build.yml
- CPU.Dockerfile
- Dockerfile
- GPU.Dockerfile
- docker-compose.yml
- docs/Deployment.md
- docs/DockerDeployment.md
- src/common/config/__init__.py
- src/common/utils/speech/text_to_speech.py
- src/plugins/chat/model.py
- src/plugins/repeater/model.py
- src/plugins/sing/__init__.py
> 支持在 `.env` 文件中更改大部分参数，新增 GPU 版本镜像 

- GPU.Dockerfile
> build: Update GPU.Dockerfile

- src/plugins/repeater/__init__.py
> feat: 管理员回复“不可以”后撤回消息

- src/plugins/greeting/__init__.py
适配shamrock等模块
牛牛打招呼的语音文件不大，用base64发送也没什么问题
> fix: 解决不同设备上语音文件不互通的问题

- src/plugins/block/__init__.py
> fix: 让牛牛认识牛牛

- src/common/config/__init__.py
> fix: 适配pydantic v1&v2

- src/plugins/block/__init__.py
- src/plugins/roulette/__init__.py
支持mongodb的用户名密码连接，在牛牛轮盘加个锁，防止多个人开枪时被全部毙掉
顺便格式化一下代码
> fix: 一些小改动

- src/plugins/repeater/__init__.py
- src/plugins/repeater/model.py
> fix: 主动发言的戳一戳简单适配

- docs/Deployment.md
> docs: fix error link & re old docs

- src/plugins/roulette/__init__.py
实装一下牛牛救一下
https://github.com/PallasBot/Pallas-Bot/issues/9#issuecomment-1547322271
> feat: 添加牛牛轮盘的解禁功能

- src/plugins/repeater/emoji_reaction.py
- 实现NapCat对自身表情回应
- 新增重试机制
- 添加10秒超时设置
> feat(repeater): 实现 NapCat 协议对自身表情回应
